apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-ci-cd-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-git
  url: https://github.com/frantz-dimitri-kube-cloud/react-ci-cd.git