apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  releaseName: my-mongo
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami-mongodb
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: mongodb-custom-values
      valuesKey: custom-values.yaml

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: my-mongo-mongodb
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/imagePullPolicy
                value: Always
