apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: 
  name: react-ci-cd-test-patch
  namespace: flux-system
spec: 
  interval: 1m0s
  path: "./k8s/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: react-ci-cd-app
  targetNamespace: flux-system
  # Debut du patch
  patches:
    - patch: |
        spec:
          replicas: 3
      target:
        kind: Deployment
        name: react-ci-cd-deployment
        namespace: default 